# Pandas Series :
    -- A Series is a one-dimensional labeled array capable of holding any data tyope. The axis labels are collectively called index

# Creating Series :
    -- There are multiple way to create a pandas series .

In [1]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\subham\appdata\roaming\python\python313\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\subham\appdata\roaming\python\python313\site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\subham\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\subham\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\subham\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\subham\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [14]:
labels=['a','b','c']
my_list=[10,20,30]
arr=np.array([10,20,30])
d={1:'x',2:'y',3:'z'}

In [ ]:
pd.Series(my_list) #noram Index

0    10
1    20
2    30
dtype: int64

In [11]:
pd.Series(my_list,index=labels) # cusom index

a    10
b    20
c    30
dtype: int64

In [12]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [15]:
pd.Series(d)

1    x
2    y
3    z
dtype: object

##  Dtaframe 
    --Combine multiple series

1.Creating a datagramr

In [22]:
data={
    "Name":["John","Anna","koustav","Lata"],
    "Age":[23,34,22,34],
    "City":["New York","San Fransisco","Paris","Busten"],
    "Salary":[10000,12000,11909,11298]
}

In [23]:
data

{'Name': ['John', 'Anna', 'koustav', 'Lata'],
 'Age': [23, 34, 22, 34],
 'City': ['New York', 'San Fransisco', 'Paris', 'Busten'],
 'Salary': [10000, 12000, 11909, 11298]}

In [25]:
df=pd.DataFrame(data)

In [26]:
df

      Name  Age           City  Salary
0     John   23       New York   10000
1     Anna   34  San Fransisco   12000
2  koustav   22          Paris   11909
3     Lata   34         Busten   11298

In [ ]:
data_list=[
    ["John",28,"Paris",10000],
    ["Amul",34,"Busten",12000],
    ["Harry",50,"Sun Fransisco",11950],
    ["Porter",45,"London",12346]
]
df2=pd.DataFrame(data_list)
# df2

        0   1              2      3
0    John  28          Paris  10000
1    Amul  34         Busten  12000
2   Harry  50  Sun Fransisco  11950
3  Porter  45         London  12346

In [29]:
column=["Name","Age","City","Salary"]
df2=pd.DataFrame(data_list,columns=column)
df2

     Name  Age           City  Salary
0    John   28          Paris   10000
1    Amul   34         Busten   12000
2   Harry   50  Sun Fransisco   11950
3  Porter   45         London   12346

**Selection And Indexing**

In [30]:
df2

     Name  Age           City  Salary
0    John   28          Paris   10000
1    Amul   34         Busten   12000
2   Harry   50  Sun Fransisco   11950
3  Porter   45         London   12346

In [37]:
df2[["Name","Age"]]

     Name  Age
0    John   28
1    Amul   34
2   Harry   50
3  Porter   45

**create a new Column**

In [38]:
df2["Designation"]=["IT","Finance","Manager","Operation"]

In [39]:
df2

     Name  Age           City  Salary Designation
0    John   28          Paris   10000          IT
1    Amul   34         Busten   12000     Finance
2   Harry   50  Sun Fransisco   11950     Manager
3  Porter   45         London   12346   Operation

**Remove a column**

In [ ]:
df2.drop("Designation",axis=1)   # this is only return a snapshot not removing  paricular columnn to actula table

     Name  Age           City  Salary
0    John   28          Paris   10000
1    Amul   34         Busten   12000
2   Harry   50  Sun Fransisco   11950
3  Porter   45         London   12346

In [41]:
df2

     Name  Age           City  Salary Designation
0    John   28          Paris   10000          IT
1    Amul   34         Busten   12000     Finance
2   Harry   50  Sun Fransisco   11950     Manager
3  Porter   45         London   12346   Operation

In [42]:
df2.drop("Designation",axis=1,inplace=True)

In [43]:
df2

     Name  Age           City  Salary
0    John   28          Paris   10000
1    Amul   34         Busten   12000
2   Harry   50  Sun Fransisco   11950
3  Porter   45         London   12346

In [ ]:
df2.drop(0,axis=0)  # this remove data column wise

     Name  Age           City  Salary
1    Amul   34         Busten   12000
2   Harry   50  Sun Fransisco   11950
3  Porter   45         London   12346

In [46]:
df2

     Name  Age           City  Salary
0    John   28          Paris   10000
1    Amul   34         Busten   12000
2   Harry   50  Sun Fransisco   11950
3  Porter   45         London   12346

**Selecting Row**

In [ ]:
df2.loc[1]    #select 1st index row

Name        Amul
Age           34
City      Busten
Salary     12000
Name: 1, dtype: object

**Seleting Subset of row and column**

In [49]:
df2

     Name  Age           City  Salary
0    John   28          Paris   10000
1    Amul   34         Busten   12000
2   Harry   50  Sun Fransisco   11950
3  Porter   45         London   12346

In [54]:
df.loc[[0,1]][["City","Salary"]]  # select 0th and 1st row 2nd and 3rd column

            City  Salary
0       New York   10000
1  San Fransisco   12000

**Conditional Selection**

In [55]:
df2

     Name  Age           City  Salary
0    John   28          Paris   10000
1    Amul   34         Busten   12000
2   Harry   50  Sun Fransisco   11950
3  Porter   45         London   12346

In [ ]:
df2[df2["Age"]>30]   # check is Age greter than 30

     Name  Age           City  Salary
1    Amul   34         Busten   12000
2   Harry   50  Sun Fransisco   11950
3  Porter   45         London   12346

In [60]:
df2[(df2["Age"]>30) & (df2["City"]=="Busten")]   # check is Age greter than 30 and city = London

   Name  Age    City  Salary
1  Amul   34  Busten   12000

**Finding Missing Data**

In [4]:
data1={
    'A':[1,2,np.nan,4,5],
    'B':[6,7,8,np.nan,10],
    'C':[11,12,13,14,np.nan],
    'D':[np.nan,17,18,19,20],
    'E':[21,np.nan,23,24,25]
}

In [5]:
df3=pd.DataFrame(data1)

In [64]:
df3

     A     B     C     D     E
0  1.0   6.0  11.0   NaN  21.0
1  2.0   7.0  12.0  17.0   NaN
2  NaN   8.0  13.0  18.0  23.0
3  4.0   NaN  14.0  19.0  24.0
4  5.0  10.0   NaN  20.0  25.0

In [65]:
df3.isna()

       A      B      C      D      E
0  False  False  False   True  False
1  False  False  False  False   True
2   True  False  False  False  False
3  False   True  False  False  False
4  False  False   True  False  False

In [66]:
df3.isna().sum()

A    1
B    1
C    1
D    1
E    1
dtype: int64

In [67]:
df.isna().any()

Name      False
Age       False
City      False
Salary    False
dtype: bool

In [ ]:
df3.dropna() # thats remove all paticulat row their any of the value is NULL -- in my case that remove all the row becuase all row have a null value

Empty DataFrame
Columns: [A, B, C, D, E]
Index: []

In [73]:
df3.dropna(thresh=3) #this check atleast 3 not null value in aparticular row

     A     B     C     D     E
0  1.0   6.0  11.0   NaN  21.0
1  2.0   7.0  12.0  17.0   NaN
2  NaN   8.0  13.0  18.0  23.0
3  4.0   NaN  14.0  19.0  24.0
4  5.0  10.0   NaN  20.0  25.0

In [6]:
df3

     A     B     C     D     E
0  1.0   6.0  11.0   NaN  21.0
1  2.0   7.0  12.0  17.0   NaN
2  NaN   8.0  13.0  18.0  23.0
3  4.0   NaN  14.0  19.0  24.0
4  5.0  10.0   NaN  20.0  25.0

**Filling the missing Data**

Remove : dropna
Search :isna
fill : fillna

In [7]:
df3.fillna(0)

     A     B     C     D     E
0  1.0   6.0  11.0   0.0  21.0
1  2.0   7.0  12.0  17.0   0.0
2  0.0   8.0  13.0  18.0  23.0
3  4.0   0.0  14.0  19.0  24.0
4  5.0  10.0   0.0  20.0  25.0

In [10]:
values={'A':0,'B':100,'C':200,'D':300,'E':400}  #like in A columr whin it is null fill o and b column whe it is null fll 100.in C column when null value fill 200 and so on 
df3.fillna(value=values)

     A      B      C      D      E
0  1.0    6.0   11.0  300.0   21.0
1  2.0    7.0   12.0   17.0  400.0
2  0.0    8.0   13.0   18.0   23.0
3  4.0  100.0   14.0   19.0   24.0
4  5.0   10.0  200.0   20.0   25.0

In [ ]:
df3.fillna(df3.mean()) #fill by mean value

     A      B     C     D      E
0  1.0   6.00  11.0  18.5  21.00
1  2.0   7.00  12.0  17.0  23.25
2  3.0   8.00  13.0  18.0  23.00
3  4.0   7.75  14.0  19.0  24.00
4  5.0  10.00  12.5  20.0  25.00